/* TODO: this file must be generated by a sequence of tests. */

#define GSKB_ALIGNOF_POINTER    4
#define GSKB_ALIGNOF_UINT64     4
#define GSKB_ALIGNOF_UINT32     4
#define GSKB_ALIGNOF_UINT16     2
#define GSKB_ALIGNOF_UINT8      1

#define GSKB_BITFIELD_ENDIANNESS  G_BYTE_ORDER

#include "gskb-bitfield-macros.h"
